nfdi4plants/nfdi4plants.knowledgebase

- src/docs/implementation/Swate.md
- src/docs/tutorials/AnnotationPatterns.md
Removed Annotation principles again. 
Updated version can be found [here](https://nfdi4plants.github.io/AnnotationPrinciples/).
> minor change

- src/docs/implementation/ArcCommanderManual/arc_access.md
- src/docs/implementation/ArcCommanderManual/arc_get.md
1. add nolfs to arc get
2. add credential manager step before arc get accesstoken
> updates to arc commander manual

- src/docs/implementation/ArcCommanderManual/arc_installation_macos.md
Easier macos installation
1. wget instead of curl 
2. make binary executable for other users on the machine
> fix macos installation

- paket.lock
After changes were done (#83), these are not visible on the website. I assume the fornax update which was required for me locally also needs to be done here and the rspective paket.lock needs to be replaced. This was done in this branch. Please check if this is the correct solution for this? @Freymaurer
> Updated fornax.

- src/docs/hidden/gitlab_timeout.md
Sorry, the docs in the hidden menu missed the yaml! 
This commit wasn't planned on the same PR. 
Fixed it now.
> hotfix: page not building

- src/docs/_sidebars/swateManualSidebar.md
- src/docs/implementation/SwateManual/swate_installation_desktop.md
- Swate Desktop installation alternatives specified
- updated Sidebar titles for Swate Desktop installation pages
- recommended for manual installation
- beta-stage for desktop installation
> Specify Swate Desktop installation alternatives 

- LICENSE
- README.md
- src/docs/CONTRIBUTING.md
1. Moved readme parts on "development" to the src/docs/CONTRIBUTING.md guide. 
2. Added description to readme
3. Changed license from MIT © @Freymaurer to CC-BY4.0.
Last point likely requires better referencing to the backend (web-components) and fornax.
> Readme, Contribution and License

- src/docs/implementation/QuickStart_swate_walkthrough.md
- src/docs/implementation/SwateManual/Docs02-Annotation-Table.md
https://github.com/nfdi4plants/Swate/issues/274
> unify-wording-createAnnoTable

- src/docs/_sidebars/arcCommanderManualSidebar.md
- src/docs/implementation/ArcCommanderManual/arc_before_we_start.md
> adapt "before we start"

- src/docs/_sidebars/mainSidebar.md
- src/docs/faqs/faqs.md
It would be great if you could a a look on the FAQ-section keeping following aspects in mind:
I saw that several Solutions to Issues are located in the KB-Issue section. One could think about starting a new doc similar to this one but with Issues/Solution or simply including it here.
> add faq section

- package-lock.json
- package.json
> update web components

- src/docs/_sidebars/mainSidebar.md
- src/docs/teaching-materials/CEPLASmeetsARCs.md
- src/docs/teaching-materials/StartYourARC.md
- src/docs/teaching-materials/index.md
- src/docs/teaching-materials/slides.md
- src/docs/teaching-materials/videos.md
This is just a first suggestion how the teaching videos could be embedded on the KB. Feel free to change it by committing to [this branch](https://github.com/nfdi4plants/nfdi4plants.knowledgebase/tree/teaching-videos-integration).
> Teaching-videos-integration

- .github/ISSUE_TEMPLATE/bug.md
- .github/ISSUE_TEMPLATE/topic-request.md
- .github/ISSUE_TEMPLATE/tutorial-request.md
- .github/pull_request_template.md
added templates for bugs, missing topics, missing tutorials and for pull requests
> add issue templates

- src/docs/guides/swate_walkthrough.md
Started polishing the swate walkthrough - not completely ready, yet, but will focus on demo example first 
- some restructuring
- added images
- adapted wording, typos
> Polish swate walkthrough

- src/docs/ArcCommanderManual/arc_before_we_start.md
> different spellings of ARC Commander :pencil2:

- src/docs/ArcCommanderManual/arc_before_we_start.md
- src/docs/_sidebars/mainSidebar.md
- src/docs/guides/tutorial_TheCommandLine.md
#147 
- put the "before we start" a level higher
- emphasize help menu
- clarify two routes of metadata input
> improve arc commander's before we start

- src/docs/_sidebars/mainSidebar.md
- src/docs/guides/ARCUserJourney.md
- src/docs/guides/BestPracticesForDataAnnotation.md
- src/docs/guides/arcCommander_QuickStart.md
- src/docs/guides/arcCommander_QuickStart_expert.md
- src/docs/guides/datahub_InviteCollaborators.md
- src/docs/guides/datahub_register.md
- src/docs/guides/index-ShareYourARC.md
- src/docs/guides/index.md
- src/docs/guides/swate_QuickStart.md
- src/docs/guides/swate_template-contribution.md
- src/docs/guides/swate_walkthrough.md
added two guides for datahub
- registration
- collaborator invitation
> add datahub guides

- src/docs/CONTRIBUTING.md
- src/docs/guides/ARCUserJourney.md
- src/docs/guides/BestPracticesForDataAnnotation.md
- src/docs/guides/arcCommander_QuickStart.md
- src/docs/guides/arcCommander_QuickStart_expert.md
- src/docs/guides/datahub_InviteCollaborators.md
- src/docs/guides/datahub_register.md
- src/docs/guides/index.md
- src/docs/guides/swate_QuickStart.md
- src/docs/guides/swate_template-contribution.md
- src/docs/guides/swate_walkthrough.md
- src/docs/teaching-materials/style/marp-theme_dataplant-ceplas-ccby.css
- src/style/style.css
1. added styling for guide badges to css
- less code on article site, central style
2. moved badges under "about this guide"
> Css test style

- src/docs/Home.md
> add note on using the knowledge base

- .github/pull_request_template.md
- Added 'Description' as a headline in the pull_request_template (@Brilator) as an enhancement for contributors and motivation to use the guide line by line.
- Executed routines.
> PR guide - added description

- src/docs/CONTRIBUTING.md
I did some changes on the coontribution guide:
- added a missing author
- updated the docs structure
- improved the relative paths section
- added examples for the references section
- corrected multiple typos
- did some minor restructuring (e.g. longer paragraph to list)
- some minor rephrasing to improve readability
> Added some changes to the contribution guide

- src/docs/faqs/faqs.md
A text in the FAQs (@CMR248 ) was pointing to steps "below" which actually are "above".
> Exchanged a word in FAQs.

- paket.lock
Updated dependencies with `npm run updatecomponents`.
fixes #44
> Updated dependencies.

- src/docs/ArcCommanderManual/arc_installation_linux.md
- src/docs/ArcCommanderManual/arc_installation_macos.md
Replaced v0.4.0 with v0.5.0 of the ARC Commander in the text in the knowledgebase.
> Updated the ARC Commander version from v0.4.0 to v0.5.0.

- src/docs/guides/swate_template-contribution.md
https://github.com/nfdi4plants/Swate-templates/issues/66
> minor edit swate templates contribution

- src/docs/guides/ARC-enablingPlatforms.md
I have only adjusted minor details. There is one general question: Is "enabling platform" a fixed term? Otherwise I would go for "Core Facility".
> changed minor details

- src/docs/ARCitect-Manual/index.md
Corrected the link to the ARCitect GitHub repository on the ARCitet welcome page in the knowledge base.
> Corrected ARCitect link

- src/docs/teaching-materials/disseminations/2023-10-CSCS-CEPLAS-StartYourARC/index.md
> publish todays slide via sidebar

- src/docs/guides/publicationToARC.md
> Publication2arc

- src/docs/SwateManual/Docs01-Installing-Swate.md
> make excel compatibility more prominent

- src/docs/guides/arcCommander_QuickStart.md
- src/docs/guides/datahub_InviteCollaborators.md
- src/docs/teaching-materials/bricks/datahub_choose-collaborator-role.md
- src/docs/teaching-materials/disseminations/2023-09-MibiNet-CEPLAS-StartYourARC/Block03b-ARCitect-HandsOn.md
- src/docs/teaching-materials/disseminations/2023-10-CSCS-CEPLAS-StartYourARC/Block03-ARCitect-HandsOn.md
- src/docs/teaching-materials/disseminations/CEPLAS-StartYourARC-Series/2023-05-31_CEPLAS-Session02/2023-05-31_CEPLAS-Session02.md
- src/docs/teaching-materials/disseminations/CEPLAS-StartYourARC-Series/2023-06-01_CEPLAS-Session03-prep/2023-06-01_CEPLAS-Session03-prep.md
- src/docs/teaching-materials/units/tutorial_019_datahub_collaboration/tutorial_019_datahub_collaboration.md
> adapt datahub role descriptions

- src/docs/_sidebars/mainSidebar.md
> move template contribution

- src/docs/implementation/OntologyServiceLandscape.md
I replaced the link the Kathryn's review paper to no longer lead to the preprint in ArXiv but rather to the accepted version in Frontiers.
> Link to Kathryn's paper in Frontiers instead of ArXiv

- src/docs/implementation/OntologyServiceLandscape.md
I missed another link to Kathryn's review. Sorry Dominik to bother you again...
> Missed one link to Kathryn's paper

- src/docs/ArcCommanderManual/arc_installation_linux.md
- src/docs/ArcCommanderManual/arc_installation_macos.md
depends on decision https://github.com/nfdi4plants/ARCCommander/issues/238
> update arc commander macos installation

- src/docs/teaching-materials/arc-user-meeting-hhu.ics
- src/docs/teaching-materials/arc-user-meeting-hhu.md
this is to test adding an ics (calendar) file for direct download from the site
> embed ics for download

- src/docs/WorkflowsManual/index.md
- src/docs/_sidebars/mainSidebar.md
Add an Index for the Workflows Manual
> Add Index for Workflows Manual

- src/docs/WorkflowsManual/cwl_metadata.md
This PR adds links and a short description to an example ARC for the previously explained concepts.
> Add links and description for example ARC

- src/docs/WorkflowsManual/cwl_runner_installation.md
Clarify the file uri scheme for the cwltool with an example and better resource link
> clarify file uri scheme for cwltool

- src/docs/teaching-materials/events-2024/2024-04-03_CEPLAS-ARC-Trainings/00-WelcomeIntro.md
- src/docs/teaching-materials/events-2024/2024-04-03_CEPLAS-ARC-Trainings/10-ARC-ecosystem-demo.md
- src/docs/teaching-materials/events-2024/2024-04-03_CEPLAS-ARC-Trainings/20-DataHUB.md
- src/docs/teaching-materials/events-2024/2024-04-03_CEPLAS-ARC-Trainings/30-MetadataISA.md
- src/docs/teaching-materials/events-2024/2024-04-03_CEPLAS-ARC-Trainings/40-DataHUB-HandsOn.md
- src/docs/teaching-materials/events-2024/2024-04-03_CEPLAS-ARC-Trainings/50-ARCitect-HandsOn.md
- src/docs/teaching-materials/events-2024/2024-04-03_CEPLAS-ARC-Trainings/70-Swate-HandsOn.md
- src/docs/teaching-materials/events-2024/2024-04-03_CEPLAS-ARC-Trainings/ARC-practical-entry-slides.md
- src/docs/teaching-materials/events-2024/2024-04-03_CEPLAS-ARC-Trainings/ARC-storageLocations.md
- src/docs/teaching-materials/events-2024/2024-04-03_CEPLAS-ARC-Trainings/README.md
- src/docs/teaching-materials/events-2024/2024-04-03_CEPLAS-ARC-Trainings/announcement.md
- src/docs/teaching-materials/events-2024/2024-04-03_CEPLAS-ARC-Trainings/index.md
- src/docs/teaching-materials/events-2024/index.md
> add placeholder container for new training series

- src/docs/guides/git-troubleshooting.md
> add to git troubles

- src/docs/guides/ComputationalWorkflows/cwl_metadata.md
This PR updates the links for the metadata example repository with the correct branch, since the previous working tree has been merged.
> Update links to CWL example repo with correct branch

- src/docs/_sidebars/mainSidebar.md
- src/docs/guides/arcitect_QuickStart_Videos.md
All Videos are uploaded to Youtube
I recreated each step of the existing arcitect quickstart and documented each step with a video
> Add Arcitect Quickstart - Videos

- src/docs/teaching-materials/events-2024/2024-04-11_MibiNet-CEPLAS-ARC-Trainings/00-Welcome.md
- src/docs/teaching-materials/events-2024/2024-04-11_MibiNet-CEPLAS-ARC-Trainings/10-Overview-DataPLANT.md
- src/docs/teaching-materials/events-2024/2024-04-11_MibiNet-CEPLAS-ARC-Trainings/15-Outlook-MibiNet-CEPLAS-HHU.md
- src/docs/teaching-materials/events-2024/2024-04-11_MibiNet-CEPLAS-ARC-Trainings/20-ARCitect-HandsOn.md
> Mibi net ceplas arc training

- src/docs/guides/swate_QuickStart.md
- src/docs/implementation/Swate.md
> fix image display in swate alpha articles

- src/docs/implementation/OntologyServiceLandscape.md
Added reference to TIB terminology service DataPLANT collection
@AngelaKranz
> Update Ontology Service Landscape article

- src/docs/_sidebars/mainSidebar.md
- src/docs/guides/swate_QuickStart_Videos.md
Adds a new SWATE Quickstart based on a video series hosted on youtube
> Add SWATE video quickstart

- src/docs/guides/ComputationalWorkflows/cwl_runner_installation.md
CC @Brilator 
Better link for the MS Windows installation instructions
Wording enhancements
Clarified that relative paths are okay, and that the input object file is optional.
> cwltool: Update install link, clarify path requirements

- src/docs/guides/ComputationalWorkflows/cwl_examples.md
- src/docs/guides/ComputationalWorkflows/cwl_metadata.md
This PR fixes dead links to cwl examples caused by merging of the example branch into the main branch. It solves #424
> Fix dead links

- src/docs/implementation/MetadataQuiz.md
> add metadaquiz page

- src/docs/_sidebars/mainSidebar.md
> another sidebar fix

- src/content/docs/resources/v1/guides/arc-AddingExternalData.md
- src/content/docs/resources/v1/guides/arc-WorkingWithBranches.md
- src/content/docs/resources/v1/guides/arc-enabling-platforms.md
- src/content/docs/resources/v1/guides/arc-galaxy.md
- src/content/docs/resources/v1/guides/arc-gitignore.md
- src/content/docs/resources/v1/guides/arc-locations.md
- src/content/docs/resources/v1/guides/arc-syncing-recommendation.md
- src/content/docs/resources/v1/guides/arc-working-with-large-data-files.md
- src/content/docs/resources/v1/guides/best-practices-for-data-annotation.md
- src/content/docs/resources/v1/guides/git-troubleshooting.md
- src/content/docs/resources/v1/guides/isa-file-types.md
- src/content/docs/resources/v1/guides/publication-to-arc.md
- src/content/docs/resources/v1/guides/tutorial-the-command-line.md
- src/content/docs/resources/v1/quickstart/arc-commander-quick-start-expert.md
- src/content/docs/resources/v1/quickstart/arc-commander-quick-start.mdx
- src/content/docs/resources/v1/quickstart/arc-user-journey.mdx
- src/content/docs/resources/v1/quickstart/arcitect-quick-start-videos.md
- src/content/docs/resources/v1/quickstart/arcitect-quick-start.md
- src/content/docs/resources/v1/quickstart/swate-quickstart-videos.md
- src/content/docs/resources/v1/quickstart/swate-quickstart.md
- src/content/docs/resources/v1/quickstart/swate-walkthrough.md
- src/content/docs/swate/swate-template-contribution.mdx
make quick start files pass development start up (propably still has dead links)
> fix quick starts

- src/content/docs/start-here/add-data.mdx
- src/content/docs/start-here/add-metadata.mdx
- src/content/docs/start-here/complete.mdx
- src/content/docs/start-here/create-arc.mdx
- src/content/docs/start-here/index.mdx
- src/content/docs/start-here/upload-to-datahub.mdx
Still needs:
- reference to cwl
> Getting Started - Violas Journey

- src/content/docs/datahub/datahub-account.mdx
- src/content/docs/start-here/05-data-analysis.mdx
- src/content/docs/start-here/06-share.mdx
> More work on Start-guide

- src/content/docs/git/git-selective-sharing.mdx
> add tutorial for selective file sharing

- src/content/docs/resources/arc-cs-code.mdx
> add draft vscode plugin

- src/content/docs/start-here/assays.mdx
- src/content/docs/start-here/data-analysis.mdx
- src/content/docs/start-here/datamap.mdx
- src/content/docs/start-here/study.mdx
solves (at least first version) of #434
> Polish viola

- src/content/docs/start-here/datamap.mdx
Just added some more introductory text and Viola interaction. Hope it's not too much text
- Data fragment selectors part
- Datamap part
> Add some more introduction text to datamap and datafragments part

- CONTRIBUTING.md
- package-lock.json
- package.json
- src/components/mdx/Mermaid.astro
- src/content/docs/start-here/assays.mdx
I added a `<Mermaid></Mermaid>` mdx component, which client side renders mermaid graphs. The styling is a bit difficult as mermaid does not easily adapth to light/dark mode. So test around and tell me if something is iffy.
@Brilator
> Setup mermaid component

- src/content/docs/git/git-troubleshooting.mdx
- extended git trouble shooting  
- add check list for debugging
> Git first aid

- package-lock.json
- src/content/docs/start-here/assays.mdx
- src/content/docs/start-here/datamap.mdx
- src/content/docs/start-here/investigation.mdx
- src/content/docs/start-here/study.mdx
fix some issues 
- https://github.com/nfdi4plants/nfdi4plants.knowledgebase/issues/509 fix only parts (readability Viola speech bubbles & Save button)
- https://github.com/nfdi4plants/nfdi4plants.knowledgebase/issues/529 changed growth temperature to temperature day 
- https://github.com/nfdi4plants/nfdi4plants.knowledgebase/issues/530 add renaming step
> Start guide overhaul

- src/content/docs/start-here/assays.mdx
- src/content/docs/start-here/create-arc-scaffold.mdx
- src/content/docs/start-here/share.mdx
- src/content/docs/start-here/study.mdx
Some small changes according to workshop feedback.
> Start guide changes

- src/content/docs/start-here/assays.mdx
- src/content/docs/start-here/study.mdx
rewrite "use template" section to current state
> rewrite "use template" section

- src/content/docs/guides/vs-code-extension.mdx
> add unavailability note on vscode ext

- src/content/docs/arc-commander/arc-commander-quick-start.mdx
https://github.com/nfdi4plants/nfdi4plants.knowledgebase/issues/560
> add note to arc commander quickstart

- src/content/docs/git/git-troubleshooting.mdx
> note on tracking lfs by size

- src/content/docs/start-here/assays.mdx
- src/content/docs/start-here/create-arc-scaffold.mdx
- src/content/docs/start-here/datamap.mdx
- src/content/docs/start-here/investigation.mdx
- src/content/docs/start-here/study.mdx
> remove steps to use optional swate save button

- src/content/docs/arcitect/installation.mdx
- src/content/docs/git/git-check.mdx
- src/content/docs/git/git-download.mdx
- src/content/docs/git/git-installation.mdx
> restructure git installation

- astro.config.mts
- src/content/docs/datahub/features/assets/gitlab-ci-arc-mermaid.yml
- src/content/docs/datahub/features/assets/gitlab-ci-arc-summary.yml
- src/content/docs/datahub/features/assets/gitlab-ci-generic.yml
- src/content/docs/datahub/features/ci-jobs.mdx
- src/content/docs/datahub/features/gitlab-ci-jobs.mdx
> add custom CI/CD

- src/content/docs/cwl/fair-data-analysis.mdx
- src/content/docs/cwl/fairify-scripts.mdx
> draft cwl-wrapping script
